<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 09:48:09
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('edit'), 'kader/edit?id='.$kader->getId(), array (
  'class' => 'sf_admin_action_edit',
)) ?></li>
</ul>
