<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 09:48:09
?>
<?php echo form_tag('kader/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($kader, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('kader[id_wilayah]', __($labels['kader{id_wilayah}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('kader{id_wilayah}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('kader{id_wilayah}')): ?>
    <?php echo form_error('kader{id_wilayah}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($kader, 'getIdWilayah', array (
  'related_class' => 'Wilayah',
  'control_name' => 'kader[id_wilayah]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('kader[id_jenis_kader]', __($labels['kader{id_jenis_kader}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('kader{id_jenis_kader}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('kader{id_jenis_kader}')): ?>
    <?php echo form_error('kader{id_jenis_kader}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($kader, 'getIdJenisKader', array (
  'related_class' => 'JenisKader',
  'control_name' => 'kader[id_jenis_kader]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('kader[nama]', __($labels['kader{nama}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('kader{nama}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('kader{nama}')): ?>
    <?php echo form_error('kader{nama}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($kader, 'getNama', array (
  'size' => 50,
  'control_name' => 'kader[nama]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('kader[alamat]', __($labels['kader{alamat}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('kader{alamat}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('kader{alamat}')): ?>
    <?php echo form_error('kader{alamat}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($kader, 'getAlamat', array (
  'size' => 50,
  'control_name' => 'kader[alamat]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('kader[rt]', __($labels['kader{rt}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('kader{rt}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('kader{rt}')): ?>
    <?php echo form_error('kader{rt}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($kader, 'getRt', array (
  'size' => 20,
  'control_name' => 'kader[rt]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('kader[rw]', __($labels['kader{rw}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('kader{rw}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('kader{rw}')): ?>
    <?php echo form_error('kader{rw}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($kader, 'getRw', array (
  'size' => 20,
  'control_name' => 'kader[rw]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('kader[no_telp]', __($labels['kader{no_telp}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('kader{no_telp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('kader{no_telp}')): ?>
    <?php echo form_error('kader{no_telp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($kader, 'getNoTelp', array (
  'size' => 20,
  'control_name' => 'kader[no_telp]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('kader' => $kader)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>
