<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 09:48:09
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('kader/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_id_wilayah"><?php echo __('Wilayah:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['id_wilayah']) ? $filters['id_wilayah'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Wilayah',
  'text_method' => '__toString',
  'control_name' => 'filters[id_wilayah]',
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_id_jenis_kader"><?php echo __('Jenis Kader:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['id_jenis_kader']) ? $filters['id_jenis_kader'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'JenisKader',
  'text_method' => '__toString',
  'control_name' => 'filters[id_jenis_kader]',
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'kader/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
