<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 09:48:09
?>
<td colspan="8">
    <?php echo $kader->getNama() ?>
     - 
    <?php echo $kader->getAlamat() ?>
     - 
    <?php echo $kader->getJenisKader() ?>
     - 
    <?php echo $kader->getWilayah() ?>
     - 
    <?php echo $kader->getRt() ?>
     - 
    <?php echo $kader->getRw() ?>
     - 
    <?php echo $kader->getNoTelp() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'kader' => $kader)) ?>
     - 
</td>