<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 09:48:09
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit kader', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('kader/edit_header', array('kader' => $kader)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('kader/edit_messages', array('kader' => $kader, 'labels' => $labels)) ?>
<?php include_partial('kader/edit_form', array('kader' => $kader, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('kader/edit_footer', array('kader' => $kader)) ?>
</div>

</div>
