<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/01 04:26:42
?>
<?php echo form_tag('pengguna/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($pengguna, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('pengguna[id_sf_guard_user]', __($labels['pengguna{id_sf_guard_user}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{id_sf_guard_user}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{id_sf_guard_user}')): ?>
    <?php echo form_error('pengguna{id_sf_guard_user}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('id_sf_guard_user', array('type' => 'edit', 'pengguna' => $pengguna)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[nama]', __($labels['pengguna{nama}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{nama}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{nama}')): ?>
    <?php echo form_error('pengguna{nama}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($pengguna, 'getNama', array (
  'size' => 50,
  'control_name' => 'pengguna[nama]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[id_wilayah]', __($labels['pengguna{id_wilayah}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{id_wilayah}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{id_wilayah}')): ?>
    <?php echo form_error('pengguna{id_wilayah}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($pengguna, 'getIdWilayah', array (
  'related_class' => 'Wilayah',
  'control_name' => 'pengguna[id_wilayah]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[keterangan]', __($labels['pengguna{keterangan}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{keterangan}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{keterangan}')): ?>
    <?php echo form_error('pengguna{keterangan}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($pengguna, 'getKeterangan', array (
  'size' => 80,
  'control_name' => 'pengguna[keterangan]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('pengguna' => $pengguna)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($pengguna->getId()): ?>
<?php echo button_to(__('delete'), 'pengguna/delete?id='.$pengguna->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
