<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/01 04:26:43
?>
    <td><?php echo $pengguna->getSfGuardUser() ?></td>
      <td><?php echo $pengguna->getNama() ?></td>
      <td><?php echo $pengguna->getWilayah() ?></td>
      <td><?php echo $pengguna->getKeterangan() ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'pengguna' => $pengguna)) ?></td>
  