<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/01 04:26:43
?>
  <th id="sf_admin_list_th_sf_guard_user">
        <?php echo __('Sf guard user') ?>
          </th>
  <th id="sf_admin_list_th_nama">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'nama'): ?>
      <?php echo link_to(__('Nama'), 'pengguna/list?sort=nama&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nama'), 'pengguna/list?sort=nama&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_wilayah">
        <?php echo __('Wilayah') ?>
          </th>
  <th id="sf_admin_list_th_keterangan">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'keterangan'): ?>
      <?php echo link_to(__('Keterangan'), 'pengguna/list?sort=keterangan&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Keterangan'), 'pengguna/list?sort=keterangan&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_opsi">
        <?php echo __('Opsi') ?>
          </th>
