<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/01 04:26:43
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'pengguna/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
