<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/01 04:26:43
?>
<td colspan="5">
    <?php echo $pengguna->getSfGuardUser() ?>
     - 
    <?php echo $pengguna->getNama() ?>
     - 
    <?php echo $pengguna->getWilayah() ?>
     - 
    <?php echo $pengguna->getKeterangan() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'pengguna' => $pengguna)) ?>
     - 
</td>