<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 04:20:12
?>
    <td><?php echo $wilayah->getWilayah() ?></td>
      <td><?php echo $wilayah->getKecamatan() ?></td>
      <td><?php echo $wilayah->getKelurahan() ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'wilayah' => $wilayah)) ?></td>
  