<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 09:51:38
?>
  <th id="sf_admin_list_th_wilayah">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/wilayah/sort') == 'wilayah'): ?>
      <?php echo link_to(__('Wilayah'), 'wilayah/list?sort=wilayah&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/wilayah/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/wilayah/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Wilayah'), 'wilayah/list?sort=wilayah&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_kecamatan">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/wilayah/sort') == 'kecamatan'): ?>
      <?php echo link_to(__('Kecamatan'), 'wilayah/list?sort=kecamatan&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/wilayah/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/wilayah/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Kecamatan'), 'wilayah/list?sort=kecamatan&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_kelurahan">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/wilayah/sort') == 'kelurahan'): ?>
      <?php echo link_to(__('Kelurahan'), 'wilayah/list?sort=kelurahan&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/wilayah/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/wilayah/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Kelurahan'), 'wilayah/list?sort=kelurahan&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_opsi">
        <?php echo __('Opsi') ?>
          </th>
