<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/22 09:34:59
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('sfGuardUser/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_username"><?php echo __('Username:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[username]', isset($filters['username']) ? $filters['username'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_groups"><?php echo __('Groups:') ?></label>
    <div class="content">
    <?php echo get_partial('groups', array('type' => 'filter', 'filters' => $filters)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'sfGuardUser/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
