<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 11:14:21
?>
    <td><?php echo link_to($sf_guard_user->getUsername() ? $sf_guard_user->getUsername() : __('-'), 'sfGuardUser/edit?id='.$sf_guard_user->getId()) ?></td>
    <td><?php echo ($sf_guard_user->getCreatedAt() !== null && $sf_guard_user->getCreatedAt() !== '') ? format_date($sf_guard_user->getCreatedAt(), "f") : '' ?></td>
      <td><?php echo ($sf_guard_user->getLastLogin() !== null && $sf_guard_user->getLastLogin() !== '') ? format_date($sf_guard_user->getLastLogin(), "f") : '' ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'sf_guard_user' => $sf_guard_user)) ?></td>
  