<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/01 01:49:44
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'sfGuardUser/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
