<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/22 04:14:43
?>
<ul class="sf_admin_actions">

<?php if($sf_user->getGuardUser()->getIsSuperAdmin() == 1) { ?>
  <li><?php echo button_to(__('list'), 'sfGuardUser/list?id='.$sf_guard_user->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
<?php } ?>

  <li><?php echo submit_tag(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>

<?php if($sf_user->getGuardUser()->getIsSuperAdmin() == 1) { ?>
  <li><?php echo submit_tag(__('save and add'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
<?php } ?>

</ul>
