<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 05:11:12
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('Lihat Daftar'), 'bankSampah/list?id='.$bank_sampah->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('Simpan'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
  <li><?php echo submit_tag(__('Simpan dan Kembali'), array (
  'name' => 'save_and_list',
  'class' => 'sf_admin_action_save_and_list',
)) ?></li>
  <li class="float-left"><?php if ($bank_sampah->getId()): ?>
<?php echo button_to(__('Hapus'), 'bankSampah/delete?id='.$bank_sampah->getId(), array (
  'post' => true,
  'confirm' => __('Hapus Data Ini?\n('.$bank_sampah->getNama().' - '.$bank_sampah->getWilayah().')'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
</ul>
