<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/01 01:43:36
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => 'home',
  'app_sf_guard_plugin_success_signout_url' => 'home',
));
