<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/01/22 10:25:15
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => 'home',
  'app_sf_guard_plugin_success_signout_url' => 'home',
));
