<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/02/01 01:43:36

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root@localhost/faskel_symfony',
), 'propel');
$this->databases['propel'] = $database;
