<?php
// auto-generated by sfValidatorConfigHandler
// date: 2018/01/22 09:35:11

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['usernameUniqueValidator'] = new sfPropelUniqueValidator();
  $validators['usernameUniqueValidator']->initialize($context, array (
  'class' => 'sfGuardUser',
  'column' => 'username',
  'unique_error' => 'This username already exists',
));
  $validators['passwordValidator'] = new sfStringValidator();
  $validators['passwordValidator']->initialize($context, array (
  'min' => 4,
  'min_error' => 'The minimum length for the password is 4',
));
  $validators['comparePasswordValidator'] = new sfCompareValidator();
  $validators['comparePasswordValidator']->initialize($context, array (
  'check' => 'sf_guard_user[password]',
  'compare_error' => 'Passwords do not match',
));
  $validatorManager->registerName('username', 1, 'Please, enter a username', 'sf_guard_user', null, false);
  $validatorManager->registerValidator('username', $validators['usernameUniqueValidator'], 'sf_guard_user');
  $validatorManager->registerName('password', 0, 'Required', 'sf_guard_user', 'password', false);
  $validatorManager->registerValidator('password', $validators['passwordValidator'], 'sf_guard_user');
  $validatorManager->registerName('password_bis', 0, 'Required', 'sf_guard_user', 'password', false);
  $validatorManager->registerValidator('password_bis', $validators['comparePasswordValidator'], 'sf_guard_user');
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
