<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/02/01 01:49:45
$this->security = array (
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 'administrator',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'administrator',
    ),
  ),
  'list' => 
  array (
    'credentials' => 
    array (
      0 => 'administrator',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
