<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/24 02:04:34
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('edit'), 'bankSampah/edit?id='.$bank_sampah->getId(), array (
  'class' => 'sf_admin_action_edit',
)) ?></li>
</ul>
