<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 05:12:19
?>
<?php echo form_tag('bankSampah/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($bank_sampah, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('bank_sampah[id_wilayah]', __($labels['bank_sampah{id_wilayah}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{id_wilayah}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{id_wilayah}')): ?>
    <?php echo form_error('bank_sampah{id_wilayah}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($bank_sampah, 'getIdWilayah', array (
  'related_class' => 'Wilayah',
  'control_name' => 'bank_sampah[id_wilayah]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[nama]', __($labels['bank_sampah{nama}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{nama}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{nama}')): ?>
    <?php echo form_error('bank_sampah{nama}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bank_sampah, 'getNama', array (
  'size' => 50,
  'control_name' => 'bank_sampah[nama]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[alamat]', __($labels['bank_sampah{alamat}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{alamat}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{alamat}')): ?>
    <?php echo form_error('bank_sampah{alamat}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bank_sampah, 'getAlamat', array (
  'size' => 50,
  'control_name' => 'bank_sampah[alamat]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[dasar_pendirian]', __($labels['bank_sampah{dasar_pendirian}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{dasar_pendirian}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{dasar_pendirian}')): ?>
    <?php echo form_error('bank_sampah{dasar_pendirian}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bank_sampah, 'getDasarPendirian', array (
  'size' => 25,
  'control_name' => 'bank_sampah[dasar_pendirian]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[tanggal_pendirian]', __($labels['bank_sampah{tanggal_pendirian}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{tanggal_pendirian}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{tanggal_pendirian}')): ?>
    <?php echo form_error('bank_sampah{tanggal_pendirian}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('tanggal_pendirian', array('type' => 'edit', 'bank_sampah' => $bank_sampah)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[bulan_pendirian]', __($labels['bank_sampah{bulan_pendirian}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{bulan_pendirian}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{bulan_pendirian}')): ?>
    <?php echo form_error('bank_sampah{bulan_pendirian}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('bulan_pendirian', array('type' => 'edit', 'bank_sampah' => $bank_sampah)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[tahun_pendirian]', __($labels['bank_sampah{tahun_pendirian}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{tahun_pendirian}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{tahun_pendirian}')): ?>
    <?php echo form_error('bank_sampah{tahun_pendirian}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bank_sampah, 'getTahunPendirian', array (
  'size' => 7,
  'control_name' => 'bank_sampah[tahun_pendirian]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[sk]', __($labels['bank_sampah{sk}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{sk}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{sk}')): ?>
    <?php echo form_error('bank_sampah{sk}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bank_sampah, 'getSk', array (
  'size' => 20,
  'control_name' => 'bank_sampah[sk]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[ketua]', __($labels['bank_sampah{ketua}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{ketua}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{ketua}')): ?>
    <?php echo form_error('bank_sampah{ketua}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bank_sampah, 'getKetua', array (
  'size' => 80,
  'control_name' => 'bank_sampah[ketua]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[jumlah_nasabah]', __($labels['bank_sampah{jumlah_nasabah}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{jumlah_nasabah}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{jumlah_nasabah}')): ?>
    <?php echo form_error('bank_sampah{jumlah_nasabah}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bank_sampah, 'getJumlahNasabah', array (
  'size' => 7,
  'control_name' => 'bank_sampah[jumlah_nasabah]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('bank_sampah[omset]', __($labels['bank_sampah{omset}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('bank_sampah{omset}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('bank_sampah{omset}')): ?>
    <?php echo form_error('bank_sampah{omset}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($bank_sampah, 'getOmset', array (
  'size' => 7,
  'control_name' => 'bank_sampah[omset]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('bank_sampah' => $bank_sampah)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>
