<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/22 10:26:07
?>
    <td><?php echo $bank_sampah->getWilayah() ?></td>
      <td><?php echo $bank_sampah->getNama() ?></td>
      <td><?php echo $bank_sampah->getAlamat() ?></td>
      <td><?php echo $bank_sampah->getDasarPendirian() ?></td>
      <td><?php echo get_partial('date', array('type' => 'list', 'bank_sampah' => $bank_sampah)) ?></td>
      <td><?php echo $bank_sampah->getSk() ?></td>
      <td><?php echo $bank_sampah->getKetua() ?></td>
      <td><?php echo $bank_sampah->getJumlahNasabah() ?></td>
      <td><?php echo get_partial('omset', array('type' => 'list', 'bank_sampah' => $bank_sampah)) ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'bank_sampah' => $bank_sampah)) ?></td>
  