<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/24 02:04:34
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Form Pengisian Data Bank Sampah', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('bankSampah/edit_header', array('bank_sampah' => $bank_sampah)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('bankSampah/edit_messages', array('bank_sampah' => $bank_sampah, 'labels' => $labels)) ?>
<?php include_partial('bankSampah/edit_form', array('bank_sampah' => $bank_sampah, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('bankSampah/edit_footer', array('bank_sampah' => $bank_sampah)) ?>
</div>

</div>
