generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Pengguna
    theme:            default
    
    list:
        display: [ sfGuardUser, nama, wilayah, keterangan, _opsi]
        fields:
            sfGuardUser:
               name: Username
    
    edit:
        display: [ _id_sf_guard_user, nama, id_wilayah, keterangan ]