<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/24 08:21:13
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('edit'), 'ipalKomunal/edit?id='.$ipal_komunal->getId(), array (
  'class' => 'sf_admin_action_edit',
)) ?></li>
</ul>
