<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/22 10:25:36
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('ipalKomunal/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_id_wilayah"><?php echo __('Wilayah:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['id_wilayah']) ? $filters['id_wilayah'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Wilayah',
  'text_method' => '__toString',
  'control_name' => 'filters[id_wilayah]',
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_tahun_pembangunan"><?php echo __('Tahun Pembangunan:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[tahun_pembangunan]', isset($filters['tahun_pembangunan']) ? $filters['tahun_pembangunan'] : null, array (
  'size' => 7,
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'ipalKomunal/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
