<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/22 10:25:37
?>
<td colspan="8">
    <?php echo $ipal_komunal->getWilayah() ?>
     - 
    <?php echo $ipal_komunal->getNama() ?>
     - 
    <?php echo $ipal_komunal->getAlamat() ?>
     - 
    <?php echo $ipal_komunal->getDasarPembangunan() ?>
     - 
    <?php echo get_partial('date', array('type' => 'list', 'ipal_komunal' => $ipal_komunal)) ?>
     - 
    <?php echo $ipal_komunal->getPengelola() ?>
     - 
    <?php echo $ipal_komunal->getKondisi() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'ipal_komunal' => $ipal_komunal)) ?>
     - 
</td>