<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/24 08:21:14
?>
    <td><?php echo $ipal_komunal->getWilayah() ?></td>
      <td><?php echo $ipal_komunal->getNama() ?></td>
      <td><?php echo $ipal_komunal->getAlamat() ?></td>
      <td><?php echo $ipal_komunal->getDasarPembangunan() ?></td>
      <td><?php echo get_partial('date', array('type' => 'list', 'ipal_komunal' => $ipal_komunal)) ?></td>
      <td><?php echo $ipal_komunal->getPengelola() ?></td>
      <td><?php echo $ipal_komunal->getKondisi() ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'ipal_komunal' => $ipal_komunal)) ?></td>
  