<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 04:20:12
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('Lihat Daftar'), 'wilayah/list?id='.$wilayah->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('Simpan'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
  <li><?php echo submit_tag(__('Simpan dan Kembali'), array (
  'name' => 'save_and_list',
  'class' => 'sf_admin_action_save_and_list',
)) ?></li>
      <li class="float-left"><?php if ($wilayah->getId()): ?>
<?php echo button_to(__('Hapus'), 'wilayah/delete?id='.$wilayah->getId(), array (
  'post' => true,
  'confirm' => __('Hapus Data Ini ?\n('.$wilayah->getWilayah().' - '.$wilayah->getKecamatan().' - '.$wilayah->getKelurahan().')'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
      <li class="float-left"><?php if ($wilayah->getId()): ?>
<?php echo link_to(image_tag('/images/delete_btn_custom.png', array('alt' => __('delete'), 'title' => __('Hapus Data'))), 'wilayah/delete?id='.$wilayah->getId(), array (
  'post' => true,
  'confirm' => __('Hapus Data Ini ?\n('.$wilayah->getWilayah().' - '.$wilayah->getKecamatan().' - '.$wilayah->getKelurahan().')'),
)) ?><?php endif; ?>
</li>
</ul>
