<?php
// auto-generated by sfPropelAdmin
// date: 2014/10/23 08:41:33

$c = new Criteria();
$wilayahSelect = WilayahPeer::doSelect($c);

?>

<?php 
    echo select_tag('wilayah[wilayah]', objects_for_select(
    $wilayahSelect,
    'getWilayah'
));
 ?>